# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Rooms-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_16f7b4a9f3794829b7f2e4012a804957 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d1571833bc1e433e97799fb357ef8a06 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_16f7b4a9f3794829b7f2e4012a804957 }}/mini-projekt-ka:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Rooms-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4f45196a90e44b6ea899e88afd3f93aa }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_16f7b4a9f3794829b7f2e4012a804957 }}/mini-projekt-ka:${{ github.sha }}'